base_url = "https://gahr.io"
title = "Arto's place on the internet"
author = "Arto Gahr"
default_language = "en"
theme = "no-style-please"
compile_sass = true
generate_feeds = true

taxonomies = [
    { name = "tags" },
]

[markdown]

[markdown.highlighting]
theme = "catppuccin-mocha"

[extra]
author = "Arto Gahr"
header_nav = [
    { name = "~home", url = "/" },
    { name = "blog", url = "/blog" },
    { name = "github", url = "https://github.com/artogahr", new_tab = true },
    { name = "contact", url = "/contact" },
]
